# Functions, File I/O, and Introduction to NumPy

Welcome to Week 4 of our Python programming course! This week, we'll cover:
- Functions and how to create reusable code
- Reading and writing files
- Working with CSV data
- Introduction to NumPy for scientific computing

As life science students, these skills will be invaluable for processing experimental data, analyzing results, and creating reproducible research workflows.

**Note**: Exercises are marked with 🥦 for required exercises and 🌶️ for optional/advanced exercises.

## Quick Review of Week 3 Concepts

Last week, we covered Python's built-in data structures:
- **Lists**: Ordered, mutable collections `[1, 2, 3]`
- **Dictionaries**: Key-value pairs `{"name": "Insulin", "molecular_weight": 5808}`
- **Sets**: Unordered collections of unique elements `{"A", "T", "G", "C"}`
- **Tuples**: Ordered, immutable collections `("BRCA1", 1756, "chromosome 17")`

## 1. Functions in Python

Functions allow you to package code into reusable blocks. In life sciences, functions can help with:
- Calculating statistics on experimental results
- Processing and transforming biological data
- Standardizing analysis workflows

### Basic Function Definition

In [2]:
# Basic function definition
def calculate_bmi(weight, height):
    """Calculate Body Mass Index.
    
    Args:
        weight: Weight in kilograms
        height: Height in meters
        
    Returns:
        The BMI value (weight / height^2)
    """
    bmi = weight / (height ** 2)
    return bmi

# Call the function with arguments
patient_bmi = calculate_bmi(70, 1.75)
print(f"Patient BMI: {patient_bmi:.2f}")

Patient BMI: 22.86


In [3]:
calculate_bmi?

Signature: calculate_bmi(weight, height)
Docstring:
Calculate Body Mass Index.

Args:
    weight: Weight in kilograms
    height: Height in meters

Returns:
    The BMI value (weight / height^2)
File:      c:\users\pasca\appdata\local\temp\ipykernel_27772\429545617.py
Type:      function

### Default Parameters and Keyword Arguments

In [ ]:
# Function with default parameters
#optional parameters is also possible
def calculate_drug_dosage(weight, age, pediatric=False, renal_impairment=False):
    """Calculate drug dosage based on patient characteristics."""
    # Base dosage calculation
    base_dosage = weight * 2
    
    # Adjust for pediatric patients
    if pediatric:
        base_dosage *= 0.75
    
    # Adjust for elderly
    if age > 65:
        base_dosage *= 0.85
    
    # Adjust for renal impairment
    if renal_impairment:
        base_dosage *= 0.6
        
    return base_dosage

# Different ways to call the function
print(f"Adult dosage: {calculate_drug_dosage(70, 45):.1f} mg")
print(f"Pediatric dosage: {calculate_drug_dosage(30, 10, pediatric=True):.1f} mg")
print(f"Elderly with renal impairment: {calculate_drug_dosage(65, 72, renal_impairment=True):.1f} mg")

### Variable Scope

In [ ]:
# Global vs. local variables
experiment_name = "Gene Expression Analysis"  # Global variable
global result = 1
def run_experiment(sample_id):
    """Simulate running an experiment."""
    print(f"Running {experiment_name} for sample {sample_id}")
    result = 42.5  # Local variable
    #return result

# Call the function
sample_result = run_experiment("BRCA001")
print(f"Experiment result: {sample_result}")

# This will cause an error because 'result' is local to the function
try:
    print(result)
except NameError as e:
    print(f"Error: {e}")

Running Gene Expression Analysis for sample BRCA001
Experiment result: None
Error: name 'result' is not defined


### 🥦 Exercise 1: Create a Protein Analysis Function

Create a function called `analyze_protein` that takes a protein sequence (string of amino acid single-letter codes) and returns a dictionary with:
- The length of the protein
- The number of hydrophobic amino acids (A, V, I, L, M, F, W)
- The percentage of hydrophobic amino acids

Test your function with the sequence: "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH" (beta-globin)

In [ ]:
# Your solution for Exercise 1
def analyze_protein(sequence):
    # Your code here
    pass

# Test with beta-globin
beta_globin = "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"
# Call your function and print the results

## 2. File I/O in Python

Working with files is essential for processing experimental data, reading configuration parameters, and storing analysis results.

### Reading and Writing Text Files

In [9]:
# First, let's create a simple text file to work with
with open('sample_data.txt', 'w') as file:
    file.write("Sample ID\tValue\tCondition\n")
    file.write("S001\t23.5\tControl\n")
    file.write("S002\t45.1\tTreatment\n")
    file.write("S003\t19.8\tControl\n")
    file.write("S004\t52.4\tTreatment\n")
    file.write("S005\t18.2\tControl\n")


In [10]:
!pwd
!dir

'pwd' is not recognized as an internal or external command,
operable program or batch file.


 Volume in drive H is Personal Drive
 Volume Serial Number is 1C37-6473

 Directory of h:\Documents\My Training\CAS\CAS_DLS\0_Tools

10/08/2025  06:58 PM    <DIR>          .
09/18/2025  11:23 AM    <DIR>          ..
10/07/2025  08:42 AM             2,376 CAS_DLS.ipynb
09/24/2025  07:50 PM           226,573 Curriculum.pdf
08/28/2025  08:45 PM    <DIR>          external
10/07/2025  08:28 AM             8,420 Intro-to-git.ipynb
10/08/2025  06:58 PM               126 sample_data.txt
10/07/2025  08:28 AM            12,344 week1.ipynb
09/23/2025  10:08 PM            17,977 week2-advanced.ipynb
10/07/2025  08:28 AM            23,105 week2.ipynb
10/08/2025  06:22 PM            12,101 week3-homework.ipynb
10/07/2025  08:28 AM            22,941 week3.ipynb
10/08/2025  05:58 PM            20,295 week4.ipynb
              10 File(s)        346,258 bytes
               3 Dir(s)  426,084,491,264 bytes free


In [11]:

# Reading line by line
print("Reading line by line:")
control_values = []
treatment_values = []

with open('sample_data.txt', 'r') as file:
    header = file.readline()  # Read the first line
    print(f"Header: {header.strip()}")
    
    # Read the rest of the lines
    for line in file:
        parts = line.strip().split('\t')
        if len(parts) == 3:
            sample_id, value, condition = parts
            value = float(value)
            
            if condition == "Control":
                control_values.append(value)
            elif condition == "Treatment":
                treatment_values.append(value)

# Calculate and print statistics
control_mean = sum(control_values) / len(control_values)
treatment_mean = sum(treatment_values) / len(treatment_values)

print(f"Control mean: {control_mean:.2f}")
print(f"Treatment mean: {treatment_mean:.2f}")

Reading line by line:
Header: Sample ID	Value	Condition
Control mean: 20.50
Treatment mean: 48.75


### 🥦 Exercise 2: FASTA File Parser

FASTA is a common format for storing DNA/protein sequences. Create a function that reads a FASTA file and returns a dictionary where the keys are sequence identifiers and the values are sequences.

Format example:
```
>Sequence1 description
ATGCAAATGCATAGCTAGCTAGCTAGCATGCATGCATGC
>Sequence2 another description
CGATGCTAGCATGCATGCTAGCATGC
```

In [12]:
# First, let's create a FASTA file to work with
with open('sample.fasta', 'w') as file:
    file.write(">sp|P68871|HBB_HUMAN Hemoglobin subunit beta\n")
    file.write("MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLG\n")
    file.write("AFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVA\n")
    file.write("NALAHKYH\n")
    file.write(">sp|P01308|INS_HUMAN Insulin\n")
    file.write("MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVEL\n")
    file.write("GGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN\n")

# Your solution for Exercise 2
def parse_fasta(filename):
    # Your code here
    pass

# Test your function
# sequences = parse_fasta('sample.fasta')
# print the results

## 3. Working with CSV Data

CSV (Comma-Separated Values) files are commonly used to store tabular data in life sciences, from experimental results to clinical data.

In [13]:
import csv

# Creating a CSV file with experimental data
with open('gene_expression.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Gene', 'Control_1', 'Control_2', 'Control_3', 'Treatment_1', 'Treatment_2', 'Treatment_3'])
    writer.writerow(['ACE2', 15.2, 14.8, 15.5, 42.3, 45.1, 39.7])
    writer.writerow(['IL6', 5.4, 4.9, 5.2, 22.8, 20.5, 25.1])
    writer.writerow(['TNF', 10.3, 11.2, 9.8, 13.5, 14.2, 12.9])
    writer.writerow(['VEGFA', 32.5, 30.8, 33.2, 25.4, 26.1, 24.8])
    writer.writerow(['TP53', 18.7, 19.2, 18.1, 17.9, 18.5, 18.3])

In [14]:
# Reading CSV data
genes = []
control_means = []
treatment_means = []
fold_changes = []

with open('gene_expression.csv', 'r') as file:
    reader = csv.reader(file)
    header = next(reader)  # Skip the header
    
    for row in reader:
        gene = row[0]
        
        # Extract control and treatment values
        control_values = [float(x) for x in row[1:4]]
        treatment_values = [float(x) for x in row[4:7]]
        
        # Calculate means
        control_mean = sum(control_values) / len(control_values)
        treatment_mean = sum(treatment_values) / len(treatment_values)
        
        # Calculate fold change
        fold_change = treatment_mean / control_mean
        
        # Store the data
        genes.append(gene)
        control_means.append(control_mean)
        treatment_means.append(treatment_mean)
        fold_changes.append(fold_change)

# Display the results
print("Gene Expression Analysis:\n")
print(f"{'Gene':<6} {'Control':<10} {'Treatment':<10} {'Fold Change':<12} {'Status'}")
print("-" * 50)

for i in range(len(genes)):
    if fold_changes[i] > 1.5:
        status = "Up-regulated"
    elif fold_changes[i] < 0.67:  # 1/1.5
        status = "Down-regulated"
    else:
        status = "No change"
        
    print(f"{genes[i]:<6} {control_means[i]:<10.2f} {treatment_means[i]:<10.2f} {fold_changes[i]:<12.2f} {status}")

Gene Expression Analysis:

Gene   Control    Treatment  Fold Change  Status
--------------------------------------------------
ACE2   15.17      42.37      2.79         Up-regulated
IL6    5.17       22.80      4.41         Up-regulated
TNF    10.43      13.53      1.30         No change
VEGFA  32.17      25.43      0.79         No change
TP53   18.67      18.23      0.98         No change


### 🌶️ Exercise 3: Gene Expression Analyzer

Create a function called `analyze_gene_expression` that:
1. Takes a CSV filename as input
2. Reads gene expression data (similar to the format above)
3. For each gene, calculates fold change and p-value using a simple t-test (use `scipy.stats.ttest_ind` if available)
4. Returns results as a list of dictionaries, one for each gene
5. Writes the results to a new CSV file

In [ ]:
# Your solution for Exercise 3
def analyze_gene_expression(filename):
    # Your code here
    pass

## 4. Introduction to NumPy

NumPy (Numerical Python) is a library for scientific computing in Python. It provides:
- Fast, efficient arrays (especially for large datasets)
- Mathematical functions for operations on these arrays
- Tools for working with linear algebra, Fourier transforms, and random numbers

In [18]:
import numpy as npx
import numpy as np

# Creating NumPy arrays
# From lists
control = npx.array([23.5, 19.8, 18.2])
treatment = npx.array([45.1, 52.4])

print(f"Control array: {control}")
print(f"Treatment array: {treatment}")

# Basic array operations
print(f"\nBasic operations:")
print(f"Mean of control: {npx.mean(control):.2f}")
print(f"Standard deviation of treatment: {npx.std(treatment):.2f}")
print(f"Sum of all values: {npx.sum(npx.concatenate([control, treatment])):.2f}")

Control array: [23.5 19.8 18.2]
Treatment array: [45.1 52.4]

Basic operations:
Mean of control: 20.50
Standard deviation of treatment: 3.65
Sum of all values: 159.00


In [19]:
# Creating arrays with specific patterns
# Array of zeros
zeros = np.zeros(5)
print(f"Array of zeros: {zeros}")

# Array of ones
ones = np.ones(5)
print(f"Array of ones: {ones}")

# Array with a range of values
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(f"Range array: {range_array}")

# Linearly spaced values
linear_space = np.linspace(0, 1, 5)  # Start, stop, number of points
print(f"Linearly spaced: {linear_space}")

# Random arrays
random_values = np.random.random(5)  # 5 random values between 0 and 1
print(f"Random values: {random_values}")

Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1.]
Range array: [0 2 4 6 8]
Linearly spaced: [0.   0.25 0.5  0.75 1.  ]
Random values: [0.81537394 0.25715155 0.72171539 0.74666876 0.63680577]


In [20]:
# Multidimensional arrays
# 2D array (matrix)
expression_data = np.array([
    [15.2, 14.8, 15.5, 42.3, 45.1, 39.7],  # ACE2
    [5.4, 4.9, 5.2, 22.8, 20.5, 25.1],     # IL6
    [10.3, 11.2, 9.8, 13.5, 14.2, 12.9],   # TNF
    [32.5, 30.8, 33.2, 25.4, 26.1, 24.8],  # VEGFA
    [18.7, 19.2, 18.1, 17.9, 18.5, 18.3]   # TP53
])

print(f"Shape of data: {expression_data.shape}")  # (rows, columns)

# Accessing elements and slices
print(f"First gene, first sample: {expression_data[0, 0]}")
print(f"Second gene, all samples: {expression_data[1, :]}")
print(f"All genes, treatment samples: {expression_data[:, 3:]}")

# Computing statistics
print(f"\nStatistics:")
print(f"Mean expression across all genes and conditions: {np.mean(expression_data):.2f}")

# Mean expression for each gene
gene_means = np.mean(expression_data, axis=1)  # axis=1 means operate across columns
print(f"Mean expression for each gene: {gene_means}")

# Mean for control vs treatment
control_means = np.mean(expression_data[:, 0:3], axis=1)
treatment_means = np.mean(expression_data[:, 3:6], axis=1)
print(f"\nControl means: {control_means}")
print(f"Treatment means: {treatment_means}")

Shape of data: (5, 6)
First gene, first sample: 15.2
Second gene, all samples: [ 5.4  4.9  5.2 22.8 20.5 25.1]
All genes, treatment samples: [[42.3 45.1 39.7]
 [22.8 20.5 25.1]
 [13.5 14.2 12.9]
 [25.4 26.1 24.8]
 [17.9 18.5 18.3]]

Statistics:
Mean expression across all genes and conditions: 20.40
Mean expression for each gene: [28.76666667 13.98333333 11.98333333 28.8        18.45      ]

Control means: [15.16666667  5.16666667 10.43333333 32.16666667 18.66666667]
Treatment means: [42.36666667 22.8        13.53333333 25.43333333 18.23333333]


In [ ]:
# Vectorized operations (much faster than loops)
fold_changes = treatment_means / control_means
log2_fold_changes = np.log2(fold_changes)

genes = ["ACE2", "IL6", "TNF", "VEGFA", "TP53"]
print("Gene Expression Analysis with NumPy:\n")
print(f"{'Gene':<6} {'Control':<10} {'Treatment':<10} {'Fold Change':<12} {'Log2 FC':<10}")
print("-" * 50)

for i in range(len(genes)):
    print(f"{genes[i]:<6} {control_means[i]:<10.2f} {treatment_means[i]:<10.2f} "
          f"{fold_changes[i]:<12.2f} {log2_fold_changes[i]:<10.2f}")

### 🥦 Exercise 4: NumPy Protein Analysis

Using NumPy, create a function that:
1. Takes a protein sequence as input
2. Calculates a hydrophobicity score for the protein using the Kyte-Doolittle scale:
   - A: 1.8, C: 2.5, D: -3.5, E: -3.5, F: 2.8, G: -0.4, H: -3.2, I: 4.5, K: -3.9, L: 3.8, 
   - M: 1.9, N: -3.5, P: -1.6, Q: -3.5, R: -4.5, S: -0.8, T: -0.7, V: 4.2, W: -0.9, Y: -1.3
3. Returns the average hydrophobicity and a sliding window analysis (window size = 7)

In [ ]:
# Your solution for Exercise 4
def analyze_hydrophobicity(sequence, window_size=7):
    # Your code here
    pass

# Test with beta-globin
beta_globin = "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"
# Call your function and print the results

## Summary

In this lesson, we've covered:
1. Functions - creating reusable code blocks
2. File I/O - reading and writing text and CSV files
3. NumPy basics - working with arrays for scientific computing

These skills will be extremely valuable as you work with biological data in your research and studies.