# Group Work

## Implement perceptron performing logical OR gate

In [11]:
import numpy as np
# define input
X = np.array( ((1,1), (1, 0), (0,1), (0,0)) )
print(X)
# set weights and biases
weights = np.array([1, 1])
threshold = -1.5
net = np.dot(X,weights)
print(net)

#compute and print output, where is bigger or equal 0 then 1 else 0
output = np.where(net + threshold >= 0, 1, 0)
print(output)

[[1 1]
 [1 0]
 [0 1]
 [0 0]]
[2 1 1 0]
[1 1 1 0]


## Vizualize decision boundary for perceptron learning logical OR gate

In [12]:
# hint: reuse the code from lecture ;)
# Let us implement the learning algorithm for the simple perceptron.

# We first import NumPy and specify the input array and the target array.
import numpy as np

# INPUT/TARGET ------------------------------------------------------------
# input
X = np.array( ((1,1), (1, 0), (0,1), (0,0)) )
# target
T = np.array([1,1,1,0])
X, T
# We set the initial weights and threshold/bias to zero.
# INITIAL WEIGHTS/BIAS -------------------------------------------
W_init = np.array([0,0])
b_init = 0
W_init, b_init
# We extend the input array and we include the bias in the weight matrix.
# EXTENDED INPUT ----------------------------------------------------------
W = np.append(W_init,b_init)
X_ext = np.hstack((X,np.ones((4,1))))
W, X_ext


(array([0, 0, 0]),
 array([[1., 1., 1.],
        [1., 0., 1.],
        [0., 1., 1.],
        [0., 0., 1.]]))

Visualize decision boundary for perceptron learning XOR gate

In [ ]:
# hint: what is the input/output difference when implementing XOR compared to OR?
# PERCEPTRON LEARNING -------------------------------------------------------
epochs = 7 #number of epochs

for n in range(epochs):
    for i in range(len(X_ext)):
        y_i = np.where(np.dot(X_ext[i,:],W) >= 0, 1, 0)
        W = W + (T[i]-y_i)*X_ext[i,:]
    print(W)
y = np.where(np.dot(X_ext,W) >= 0, 1, 0)
#  Let us look at the target and the output and the weights found by the algorithm.
print(T)
print(y)
print(W)

[ 0.  0. -1.]
[ 1.  1. -1.]
[ 1.  1. -1.]
[ 1.  1. -1.]
[ 1.  1. -1.]
[ 1.  1. -1.]
[ 1.  1. -1.]
[1 1 1 0]
[1 1 1 0]
[ 1.  1. -1.]


## Implement multilayer perceptron that computes XOR
### note: only implement it ans assume step activation function - it is not learning - see exmaple for simple neuron implementation

hint: use simple weignts and biases. i.e. +-1

In [13]:
# MLP for XOR
# input
X = np.array( ((1,1), (1, 0), (0,1), (0,0)) )

# extended input
X_ext =np.hstack((X,np.ones((4,1))))

# target
T = np.array([0,1,1,0])
print(X)
print(X_ext)

[[1 1]
 [1 0]
 [0 1]
 [0 0]]
[[1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [33]:
# Specify a set of predefined weights that allow to implement the XOR function
# Include the biases in the weight arrays

# WEIGHTS/BIAS FOR FIRST NODE IN HIDDEN LAYER
W_h1_init = np.array([1, 1]) # fill in your weights
b_h1_init = -1 # fill in your bias
# EXTENDED
W1_h1 = np.append(W_h1_init,b_h1_init)

#X_ext = np.hstack((X,np.ones((4,1))))
print(W1_h1)

# WEIGHTS/BIAS FOR SECOND NODE IN HIDDEN LAYER
W_h2_init = np.array([-1, -1]) # fill in your weights
b_h2_init = 1 # fill in your bias
# EXTENDED
W2_h1 = np.append(W_h2_init,b_h2_init)
#X_ext2 = np.hstack((X,np.ones((4,1))))
print(W2_h1)

#Node in the output layer
W_y_init = np.array([1,1])
b_y_init =-2
W_y =np.append(W_y_init,b_y_init)


print(W_y_init,W_y)


[ 1  1 -1]
[-1 -1  1]
[1 1] [ 1  1 -2]


In [34]:
# Compute the output of the hidden layer
# FIRST NODE
net_h1 = np.dot(X_ext,W1_h1)
h1 = np.where(net_h1 >= 0, 1, 0)

# SECOND NODE
net_h2 = np.dot(X_ext,W2_h1)
h2 = np.where(net_h2 >= 0, 1, 0)
# The output of the hidden layer is the input to the final layer.
h1, h2
# INPUT FOR OUTPUT LAYER
X_h = np.column_stack((h1,h2))
# EXTENDED INPUT FOR OUTPUT LAYER----------------------------------------------------------
X_h_ext = np.hstack((X_h,np.ones((4,1))))
# We can then compute the final output, confirming that indeed the XOR function is implemented correctly.
net = np.dot(X_h_ext,W_y)
y = np.where(net >= 0, 1, 0)

print(y)
print(T)


[0 1 1 0]
[0 1 1 0]


In [ ]:
# INPUT FOR OUTPUT LAYER - combine h1 and h2
X_h =
# EXTENDED INPUT FOR OUTPUT LAYER----------------------------------------------------------
X_h_ext =

# Compute the final output, confirming that indeed the XOR function is implemented correctly.
net =
y =

print(y)
print(T)